name: CD Pipeline

on:
  release:
    type: [CD]
  workflow_dispatch:
    inputs:
      releaseType:
        description: "where do deploy"
        required: true
        default: 'production'
env:
  AWS_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  SERVER_PUBLIC_IP: ${{ secrets.AWS_PUBLIC_KEY }}
jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy docker image to EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: medeci
          IMAGE_TAG: latest #${{ github.sha }}
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_SSH_KEY }}
          envs: PRIVATE_SSH_KEY,ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_REGION
          uses: aws-actions/amazon-ecr-login@v1
          script: |-
            aws sts get-caller-identity
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 296274010522.dkr.ecr.eu-west-1.amazonaws.com
            docker push 296274010522.dkr.ecr.eu-west-1.amazonaws.com/medeci:latest
            docker run -d --name myappcontainer -p 80:80 296274010522.dkr.ecr.eu-west-1.amazonaws.com/medeci:latest